CREATE USER osmreader WITH PASSWORD 'osmreader';
GRANT CONNECT ON DATABASE osm TO osmreader;
GRANT USAGE ON SCHEMA public TO osmreader;
GRANT USAGE ON SCHEMA o2pg TO osmreader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO osmreader;
GRANT SELECT ON ALL TABLES IN SCHEMA o2pg TO osmreader;
-- Give read access to all future tables
ALTER DEFAULT PRIVILEGES FOR ROLE osm IN SCHEMA public GRANT SELECT ON TABLES TO osmreader;
ALTER DEFAULT PRIVILEGES FOR ROLE osm IN SCHEMA o2pg GRANT SELECT ON TABLES TO osmreader;
